feellikeit/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.new, name='new'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feellikeit/', include('feellikeit.urls')),
    path('whynot/', include('whynot.urls'))
]

whynot/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

feellikeit/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class FeelLikeIt(models.Model):
    date = models.DateTimeField(default=timezone.now)
    reason = models.TextField(default="Maybe it's just too boring.")
    snap = models.ImageField(upload_to='snap', default='/pics/never_mind.png')
    no = models.TextField(default="Just simply don't do that.")

    def __str__(self):
        return str(self.date)

whynot/models.py
from django.db import models


# Create your models here.
class Category(models.Model):
    catName = models.CharField(max_length=1000)

    def __str__(self):
        return self.catName


class Dos(models.Model):
    cat = models.ForeignKey(Category, on_delete=models.CASCADE)
    dos = models.CharField(max_length=1000)

    def __str__(self):
        return self.dos

feellikeit/views.py
from django.shortcuts import render
from .models import FeelLikeIt
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse


# Create your views here.
def index(request):
    times = FeelLikeIt.objects.count()
    last_time = FeelLikeIt.objects.last().date
    content = {
        "times": times,
        "last_time": last_time,
    }
    return render(request, 'feellikeit/statics.html', content)


def new(request):
    if request.method == "GET":
        return render(request, 'feellikeit/new.html')
    if request.method == "POST":
        date = request.POST.get("date")
        reason = request.POST.get("reason")
        snap = request.FILES.get("snap")
        no = request.POST.get("no")
        FeelLikeIt.objects.create(date=date, reason=reason, snap=snap, no=no)
        return HttpResponseRedirect(reverse('index'))

whynot/views.py
from django.shortcuts import render
from .models import Category, Dos
# Create your views here.


def index(request):
    cats = Category.objects.all()

    return render(request, 'whynot/whynot.html', {"content": cats})

templates/feellikeit/new.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Feel like it?</title>
    <link rel="shortcut icon" type="image/x-icon" href={% static "pics/bitbug_favicon.ico" %} >
    <link rel="stylesheet" href={% static 'css/feellikeit.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
</head>

<body>
    <div class="container input-area"><strong style="margin: 20px;font-size: 30px;">Feel Like it?</strong>
        <form class="input-form" method="post" enctype="multipart/form-data" action="{% url 'new' %}">
            {% csrf_token %}
            <div class="input-row"><label for="date">When?</label><input class="form-control" type="datetime-local" name="date" id="date" required></div>
            <div class="input-row"><label for="reason">Why?</label><input class="form-control" type="text" name="reason" id="reason" required></div>
            <div class="input-row"><label for="snap">Evidence?</label><input type="file" name="snap" required="" accept="image/*" id="snap"></div>
            <div class="input-row"><label for="no">No!</label><input class="form-control" type="text" name="no" id="no" required></div><button class="btn btn-primary" type="submit"><strong>だが断る！</strong><br></button></form>
    </div>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    <script src={% static 'js/jquery.min.js' %}></script>
</body>

</html>

templates/feellikeit/statics.html
<!DOCTYPE html>
<html>
{%  load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Feel Like It</title>
    <link rel="shortcut icon" type="image/x-icon" href={% static "pics/bitbug_favicon.ico" %} >
    <link rel="stylesheet" href={% static 'css/feellikeit.css' %}>
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
    <link rel="stylesheet" href={% static 'css/Highlight-Blue.css' %}>
</head>

<body>
    <div class="highlight-blue" style="height: 100vh;width: 100vw;padding: 50px 0;">
        <div class="container">
            <div class="intro">
                <h2 class="text-center">Feel like it?</h2>
                <p class="text-center">You have felt like it for <span style="font-size: 2em"> {{ times }} </span>  times.</p>
                <p class="text-center">You haven't felt like it since : {{ last_time }}</p>
            </div>
            <div class="buttons"><a class="btn btn-primary" role="button" href={% url 'new' %}>I'm feeling like it!</a></div>
        </div>
    </div>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    <script src={% static 'js/jquery.min.js' %}></script>
</body>

</html>

templates/whynot/whynot.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Why Not?</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Bitter:400,700">
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}>
</head>

<body>
    <header>
        <h1>Why Not?</h1>
    </header>
    <main>
        {% for cat in content %}
            <div class="container">
                <h2>{{ cat.catName }}？</h2>
                <ul class="list-group">
                    {% for dos in cat.dos_set.all %}
                        <li class="list-group-item"><span>{{ dos.dos }}？</span><input type="text"></li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </main>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    <script src={% static 'js/jquery.min.js' %}></script>
</body>

</html>